run:
  timeout: 5m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    shadow: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 15
  lll:
    line-length: 120
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - gocyclo
    - dupl
    - funlen
    - gocognit
    - lll
    - nakedret
    - noctx
    - nolintlint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - funlen
        - gocognit
  max-issues-per-linter: 0
  max-same-issues: 0
