openapi: 3.0.3
info:
  title: Todo Service
  description: Todo Service
  version: 1.0.0
servers:
  - url: 'http://localhost:8681'
components:
  schemas:
    Task:
      type: object
      properties:
        title:
          type: string
x-weos-config:
  database:
    driver: sqlite3
    database: tasks.db
paths:
  /tasks:
    post:
      operationId: createTask
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        201:
          description: Created Task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
    get:
      operationId: getTasks
      responses:
        200:
          description: List of blogs
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  page:
                    type: integer
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Task"
  /tasks/{id}:
    get:
      operationId: getTask
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
        - in: query
          name: sequence_no
          schema:
            type: integer
      responses:
        200:
          description: Task Details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
    put:
      operationId: updateTask
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        200:
          description: Updated Task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
    delete:
      operationId: deleteTask
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      x-schema: "Task"
      responses:
        200:
          description: Deleted Task



