name: Development Workflow
on:
  push:
    branches:
      - dev
      - feature/*
      - release/*

env:
  SLACK_CHANNEL: weos
  SLACK_USERNAME: WeOS CI
  SLACK_ICON: https://github.com/wepala.png?size=48
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  SLACK_FOOTER: copyright 2021 Wepala

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      today: ${{ steps.date.outputs.today }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Run Sqlite3 integration tests
        run: go test -v ./...
      - name: Run Postgres projections tests
        run: go test -v ./projections -driver=postgres
      - name: Run Mysql projections tests
        run: go test -v ./projections -driver=mysql
      - name: Send release notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: "FFFF00"
          SLACK_MESSAGE: We were able to create a development build. Get the artifact here https://github.com/wepala/weos-service/actions/runs/${{ github.run_id }}
          SLACK_TITLE: WeOS Build Created